<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        \App\Models\User::create([
            'name' => 'Muhamad Zafar Syah',
            'email' => 'tes@gmail.com',
            'password' => bcrypt('12345'),
        ]);

        \App\Models\User::create([
            'name' => 'admin',
            'email' => 'admin@gmail.com',
            'password' => bcrypt('12345'),
            'role' => 'admin',
        ]);

        $name = [
            'Teh Pucuk',
            'Milo',
            'Indomilk',
            'Milku',
            'You C 1000',
            'Pocari Sweat',
            'Cincau Cap Panda',
            'Larutan Kaleng',
            'Nescafe',
            'Bear Brand',
            'Susu Ultra',
            'Sari Kacang Hijau',
            'Susu Cimory',
            'Galon Oce',
            'Galon Aqua (kantin)',
            'Refill Air Botol',
            'Refill Air Botol',
            'Buku',
            'Correction Tape',
            'Penggaris',
            'Pensil',
            'Rautan',
            'Penghapus',
            'Spidol',
            'SKU Kuning',
            'Roti Padimas',
            'Roti Sisir Nanas',
            'French Fries',
            'Kacang Sukro',
            'Chitato Lite',
            'Happy Tos',
            'Garuda Puffy Stick',
            'Popcorn',
            'Tic Tic',
            'Garuda Skippy',
            'Gery Snack Pillow',
            'Beng-beng',
            'Nextar Nastar/Nextar Star',
            'Slai Olai',
            'Choco Pie',
            'Oreo Original',
            'Good Time',
            'Wafello',
            'Biskuit Roma',
            'Tango',
            'Mini Astor',
            'Pilus Garuda Rendang',
            'Sari Gandum',
            'Pasta',
            'Kriuk Hijau',
            'Mie Kremezz',
            'Chocolatos',
            'Gery Salut',
            'Malkist',
            'Gorio rio',
            'Chuba',
            'Kerupuk Udang',
            'Kerupuk Tahu',
            'Basreng',
            'Kacang Balado',
            'Keripik Kaca',
            'Capung',
            'Chacha',
            'Kerupuk Rambak',
            'Kerupuk Cabe',
            'Milkita',
            'Permen Kaki, Pendekar biru',
            'Davos',
            'Teh Kotak'
        ];

        $harga = [
            4000,
            6000,
            6000,
            3500,
            7000,
            7000,
            7000,
            7000,
            8000,
            11000,
            7000,
            7000,
            7000,
            16000,
            6000,
            1000,
            2000,
            6000,
            5000,
            4000,
            4000,
            3000,
            3000,
            3000,
            5000,
            2500,
            2500,
            2000,
            2000,
            2000,
            2000,
            2000,
            2000,
            2000,
            2000,
            2000,
            2500,
            2000,
            2000,
            2500,
            2000,
            2000,
            2000,
            2000,
            2000,
            2000,
            1000,
            2000,
            1000,
            2000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            2000,
            7000
        ];

        $category_slug = [
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'lainnya',
            'lainnya',
            'lainnya',
            'lainnya',
            'alat-tulis',
            'alat-tulis',
            'alat-tulis',
            'alat-tulis',
            'alat-tulis',
            'alat-tulis',
            'alat-tulis',
            'alat-tulis',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan',
            'jajanan'
        ];

        $category = [
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Lainnya',
            'Lainnya',
            'Lainnya',
            'Lainnya',
            'Alat Tulis',
            'Alat Tulis',
            'Alat Tulis',
            'Alat Tulis',
            'Alat Tulis',
            'Alat Tulis',
            'Alat Tulis',
            'Alat Tulis',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan',
            'Jajanan'
        ];

        $type = [
            null,
            'Cokelat',
            'Cokelat',
            'Cokelat, Full Cream, Strawberry',
            null,
            null,
            null,
            'Leci',
            'Latte, Caramel, Ice Black, Cappucino',
            null,
            'Cokelat, Full Cream, Strawberry',
            null,
            'Almond, Cashew, Strawberry, Coklat Tiramisu',
            null,
            null,
            'Tanpa Es Batu',
            'Dengan Es Batu',
            null,
            null,
            null,
            null,
            null,
            null,
            'Hitam, Merah',
            null,
            'Keju, Es teler, Mix Fruit',
            null,
            null,
            null,
            null,
            null,
            null,
            'Caramel, Mentega, Cokelat',
            null,
            null,
            null,
            null,
            'Nanas dan Strawberry Vanila',
            'Nanas',
            null,
            null,
            null,
            'Cokelat',
            null,
            'Coconut',
            null,
            null,
            'Cokelat',
            'Cokelat, Keju',
            null,
            'Balado, Ayam Panggang',
            null,
            'Matcha',
            'Keju, Cokelat',
            null,
            'Keju, Balado',
            null,
            null,
            'Asin, Balado',
            null,
            null,
            null,
            'Kacang, Cokelat',
            null,
            null,
            'Cokelat, Strawberry, Melon',
            null,
            null,
            null
        ];

        // Generate dynamic data based on rules
        $image = array_map(fn($n) => 'products/' . Str::slug($n) . '.webp', $name);
        $stock = array_map(fn() => rand(1, 40), $name);
        $description = array_fill(0, count($name), 'semua murah meriah');
        $type = array_map(fn($t) => $t ? json_encode(array_map('trim', explode(',', $t))) : null, $type);

        $data = [];

        for ($i = 0; $i < count($name); $i++) {
            $data[] = [
                'name' => $name[$i],
                'image' => $image[$i],
                'stock' => $stock[$i],
                'price' => $harga[$i],
                'description' => $description[$i],
                'type' => $type[$i],
                'category' => $category[$i],
                'category_slug' => $category_slug[$i],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ];
        }

        DB::table('products')->insert($data);
    }
}
